<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Last</name>
   <tag></tag>
   <elementGuidId>14adfd46-c7c4-47e3-bd5b-2e9dbf212435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[4]/div[4]/ul/li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11da8047-4478-4ea2-9e90-5b645d97c60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>64ad5260-980d-4858-8951-78aded851154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Last</value>
      <webElementGuid>b02b1174-6749-45d7-a736-db4429c84f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link ml-1 fs-14</value>
      <webElementGuid>3649a2e6-0a85-4702-a0a0-848d232f4299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Last
        </value>
      <webElementGuid>d44bc634-347f-4d19-8f45-90829e9767c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/div[4]/div[@class=&quot;job-list-container&quot;]/ul[@class=&quot;pagination justify-content-center align-items-center&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link ml-1 fs-14&quot;]</value>
      <webElementGuid>ed6c3426-31ef-4487-994d-66a158ba0918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[4]/div[4]/ul/li[10]/a</value>
      <webElementGuid>fcceca2c-e8ec-4395-b3d2-26a89ddbfef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Last')]</value>
      <webElementGuid>410a7e2e-e8c1-4965-96f5-dae44679de52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replied'])[12]/following::a[10]</value>
      <webElementGuid>555ef577-1360-42c1-99ec-e97c79d6559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacted'])[12]/following::a[10]</value>
      <webElementGuid>472cc902-7ed9-4854-927f-b8b8f6d7793e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reaching out to 0 talents'])[1]/preceding::a[1]</value>
      <webElementGuid>89da4536-e960-4120-aa87-5e8a201f98d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimize'])[1]/preceding::a[1]</value>
      <webElementGuid>866c9488-8d2b-4b88-81d9-e5f3d6a5d931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last']/parent::*</value>
      <webElementGuid>5e1a1767-9a7b-4172-92b7-7837e44f1d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>e3285bc7-d6be-48d6-a3e8-142df04f947f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>840e5801-6162-4494-9239-b5c07c5a5846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
            Last
        ' or . = '
            Last
        ')]</value>
      <webElementGuid>84e6d7de-b9b9-472c-bf03-fa5e8ce90f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
