<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>last button</name>
   <tag></tag>
   <elementGuidId>f0738db8-6a8f-43fd-88b3-1e7f5886f9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88be694d-67df-417a-a0fe-3f3e3da7d153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4026cff3-fc06-4239-a00e-40a9e661ecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Last</value>
      <webElementGuid>9f37c8b0-0f52-4797-ba02-ad698e6145da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link ml-1 fs-14</value>
      <webElementGuid>519b2622-b5fa-43b4-9855-69b96d4c79c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Last
        </value>
      <webElementGuid>7b4bf1b6-5b55-4805-9d71-5c125f85f911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/div[4]/div[@class=&quot;job-list-container&quot;]/ul[@class=&quot;pagination justify-content-center align-items-center&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link ml-1 fs-14&quot;]</value>
      <webElementGuid>2041ea28-d1cf-4cd2-a222-9a727419ab2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[4]/div[4]/ul/li[10]/a</value>
      <webElementGuid>2031d0fc-fb96-49a3-83e8-b8fa3a426876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Last')]</value>
      <webElementGuid>472c0e49-309f-4678-b700-0f4c4f920c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replied'])[12]/following::a[10]</value>
      <webElementGuid>4a564959-e89b-4c1e-9ced-996f9cfd1a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacted'])[12]/following::a[10]</value>
      <webElementGuid>b9ea11f6-8856-4d88-84b6-54986f8f04da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reaching out to 0 talents'])[1]/preceding::a[1]</value>
      <webElementGuid>904ec81c-2b87-4ca5-b5c1-1b63d2f26a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimize'])[1]/preceding::a[1]</value>
      <webElementGuid>4af92eda-fabe-4f34-b9bc-bfc009e61f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last']/parent::*</value>
      <webElementGuid>491ebdbb-c746-4854-956d-6d4655bec45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>7091f1cb-fa66-4998-921a-db05d38fc3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>9631e512-ad9e-41fc-bea9-0b55ff3894a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
            Last
        ' or . = '
            Last
        ')]</value>
      <webElementGuid>951aa43c-20e7-4d0c-b8e2-2facf6c4b31e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
