<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>project navbar</name>
   <tag></tag>
   <elementGuidId>b3d48005-2370-49e3-b1f5-b7ce3342b500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-projects</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d026d35d-2781-4080-bf25-70ae999debc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.shortlyst.ai/sourcing/jobs</value>
      <webElementGuid>f8f78286-4a14-42b2-98af-4a4d24b25a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-projects</value>
      <webElementGuid>cde05209-8bba-47e8-a8c4-4b28c7afc51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link pt-xxl-3 pb-xxl-2</value>
      <webElementGuid>a22397b9-5117-41ff-a912-bb26ca2ab65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Projects</value>
      <webElementGuid>18080803-e7b9-4e54-9bb1-de9d289583b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-projects&quot;)</value>
      <webElementGuid>09f66d77-d4e2-4e6a-830d-8f991b3af947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-projects']</value>
      <webElementGuid>6a16ec1e-ca07-467d-84c3-e4edc52f41b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo01']/ul/li[2]/a</value>
      <webElementGuid>b52b2749-e8a7-40f3-b338-ba2b21929225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Projects')]</value>
      <webElementGuid>e8677d00-4354-4f59-ad00-2e3ecd1121c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>516401f1-1f8a-4f44-97ef-eeb1d6ea7175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integration'])[1]/preceding::a[2]</value>
      <webElementGuid>c080e072-1215-464d-9497-2183c8eec98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Projects']/parent::*</value>
      <webElementGuid>1305d209-75fe-42a2-8adf-a56f9cb311d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app.shortlyst.ai/sourcing/jobs')]</value>
      <webElementGuid>ba11dc1f-e875-4c02-9125-9a3ea5c7bd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>3ede5620-6f56-4ae0-9273-c84d38160b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app.shortlyst.ai/sourcing/jobs' and @id = 'menu-projects' and (text() = ' Projects' or . = ' Projects')]</value>
      <webElementGuid>9c8b5bb3-a045-4d15-be60-5ed7e12b93b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
